# Generated by Django 4.2.5 on 2023-11-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='media/aboutus/%Y%m%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='aboutus',
        ),
    ]
