# Generated by Django 4.2.5 on 2023-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_objectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/aboutus/%Y%m%d/')),
            ],
        ),
    ]
