# Generated by Django 4.2.5 on 2023-11-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_stats_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats_img',
        ),
    ]
