# Generated by Django 4.2.5 on 2023-11-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_delete_stats_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/people/%Y%m%d/')),
            ],
        ),
    ]
