# Generated by Django 4.2.5 on 2023-11-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_peopleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=225)),
                ('event_description', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='media/events/%Y%m%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='PeopleImage',
        ),
    ]
