# Generated by Django 4.2.5 on 2023-11-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_event_delete_peopleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/event_images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.event')),
            ],
        ),
    ]
