# Generated by Django 4.2.7 on 2023-11-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_eventimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
