# Generated by Django 4.2.7 on 2023-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_recentpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('post_link', models.CharField(max_length=225)),
                ('post_image', models.ImageField(upload_to='media/team/%Y%m%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='RecentPost',
        ),
    ]
