# Generated by Django 4.2.7 on 2024-01-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0017_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='media/people/%Y%m%d/')),
                ('role', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
