# Generated by Django 4.2.5 on 2023-11-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('front_image', models.ImageField(upload_to='media/shop_now_home_front/%Y%m%d/')),
                ('back_image', models.ImageField(upload_to='media/shop_now_home_back/%Y%m%d/')),
                ('button_text', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Shop_now',
        ),
    ]
