# Generated by Django 4.2.7 on 2023-11-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_shop_delete_shop_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_now',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='media/shop_now_home_front/%Y%m%d/')),
                ('price', models.ImageField(upload_to='media/shop_now_home_back/%Y%m%d/')),
            ],
        ),
    ]
