# Generated by Django 4.2.7 on 2024-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shop_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_now',
            name='image',
            field=models.ImageField(upload_to='media/products/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='shop_now',
            name='price',
            field=models.CharField(max_length=225),
        ),
    ]
